apiVersion: v1
kind: Pod
spec:
  tolerations:
%{ for toleration in tolerations ~}
  - key: "${toleration.key}"
    operator: "${toleration.operator}"
    effect: "${toleration.effect}"
%{ endfor ~}
  containers:
  - name: spark-kubernetes-driver
